### ISSUE TITLE
Remove previous day from view

### ISSUE THREAD

**Issue by AT-Studio** [miso01/SingleRowCalendar#1]
It seems that previous day stays in the list unless the user restarts the app. In my use case I don't care about days before the current day. Is there a way for me to discard the previous day?

**Comment by misosvec** [comment]
I don't know if I understand you well, but you can specify your own list of dates in code or you can just simply use futureDaysCount attribute.

**Comment by AT-Studio** [comment]
I believe I have found a solution to my problem :) Thank you for the quick reply!
