### ISSUE TITLE
Could not find com.michalsvec:single-row-calednar:1.0.0.

### ISSUE THREAD

**Issue by kelalaka153** [miso01/SingleRowCalendar#28]
I'm using Android Studio Giraffe | 2022.3.1 Patch 3 with 

        compileSdk = 34
        minSdk = 30
        targetSdk = 34

wrote this ino build.gradle/kts

dependencies {
...
`implementation ("com.michalsvec:single-row-calednar:1.0.0")`
...
}

And this error

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.michalsvec:single-row-calednar:1.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/michalsvec/single-row-calednar/1.0.0/single-row-calednar-1.0.0.pom
       - https://repo.maven.apache.org/maven2/com/michalsvec/single-row-calednar/1.0.0/single-row-calednar-1.0.0.pom
     Required by:
         project :app

Look around and couldn't find a solution. 

How can I resolve this issue?

**note that** I've tested with https://github.com/hdodenhof/CircleImageView library and it installed fine.

**Comment by Dawid-Witkowski** [comment]
the searched locations didn't include Jcenter, might have been the reason :)

**Comment by kelalaka153** [comment]
```
repositories {
    maven { url = uri("https://jcenter.bintray.com") }
    
```

This is the  solution!
